project:
  type: book
  output-dir: docs

book:
  title: "ESIP Biological Data Cluster (BDS) Primer Guide"
  author: "ESIP Biological Data Cluster"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - CONTEXT_UNDERSTANDABILITY.qmd
    - INTEGRATE_DATA.qmd
    - INTEROPERABLE_DATA.qmd
    - MAKE_YOUR_DATA_INTERNET_READY.qmd
    - SOFTWARE_READY.qmd

number-depth: 2
number-offset: 1
  
execute:
  echo: FALSE
  warning: FALSE
  message: FALSE
  freeze: auto

#bibliography: references.bib

format:
  html:
   code-links:
      - text: Github Repo
        icon: github
        href: https://github.com/ESIPFed/bds-primer-best-practices
      - text: Give feedback on this page
        icon: lightbulb
        href: https://github.com/ESIPFed/bds-primer-best-practices/issues/new/choose
   theme: cosmo
   link-external-icon: true
   link-external-newwindow: true
   link-external-filter: '^(?:http:|https:)\/\/esipfed\.github\.io'
   toc: false
   
  pdf: default
  docx: 
    toc: false  # This isn't populating for some reason
    fig-align: center
    #tbl-colwidths: auto
    lang: en
    reference-doc: custom-reference-doc.docx
      
editor: visual

