# Make Your Data Interoperable

Controlled vocabularies can provide standardized terms and definitions for biological concepts, like biological taxonomies. Using a controlled vocabulary facilitates the integration and sharing of data across diverse sources, improving consistency and data quality, for example, in species classification.

## Catalogue of Life (COL)

### What Is It?

[Catalogue of Life](https://www.catalogueoflife.org/) describes itself as, “The most complete authoritative list of the world's species - maintained by hundreds of global taxonomists.” It brings together information from taxonomists, and taxonomic databases, to construct an integrated view of currently accepted species across all taxonomic groups. A list of source datasets can be found [here](https://www.catalogueoflife.org/data/source-datasets).\
\
The primary mission of COL is to deliver data, but the tools and services offered by COL also enable taxonomists and other stakeholders to publish and revise species lists for any purpose.

### **Why?**

-   COL adds persistent identifiers that enable users to track changes to a scientific name. 

-   COL helps downstream users consider the most up-to-date past and current characteristics of an organism: its biology, distribution, relevance to humans, and evolutionary history.

### **Top Resources**

-   Users can browse the [COL Checklist](https://www.catalogueoflife.org/data/browse), which is updated monthly. COL pulls information from specific data sources, e.g. FishBase (see: <https://www.catalogueoflife.org/data/taxon/49JFH>). 

-   COL data pipeline for COL taxonomic checklist data: <https://www.catalogueoflife.org/about/colpipeline>. 

-   COL ChecklistBank API: <https://api.checklistbank.org/>.

## Integrated Taxonomic Information System (ITIS)

### What Is It?

[ITIS](https://www.itis.gov/) is a taxonomic database, developed and maintained by a partnership of federal agencies that provides reliable information on the nomenclature, taxonomy, and distribution of 1.8 million species of plants, animals, fungi and microbes in North America and the world. ITIS couples each scientific name with a unique taxonomic serial number (TSN), which ensures consistency and accuracy in the naming and classification of species.

### **Why?**

-   Unique taxonomic serial number (TSN) ensures consistent and accurate naming and classification of species

-   ITIS is an important tool for identifying and cataloging species and monitoring their populations. 

### **Top Resources**

-   [ITIS website](https://www.itis.gov/) 

-   ITIS [API](https://itis.gov/web_service.html)

## Paleobiology Database (PBDB)

### What Is It?

The [Paleobiology Database](https://paleobiodb.org/) (PBDB) is an online, expert-curated database that aims to provide taxonomic information for paleobiological taxa of all geological ages. It contains data for almost half a million paleobiological taxa from over 900 different contributors.

### **Why?**

-   Checking your paleobiological taxonomic names against the PBDB will ensure the names are up-to-date based on current taxonomic literature as reflected in the database.

-   PBDB provides the taxonomic backbone to the Global Biodiversity Information Facility (GBIF). This means aligning your taxonomic names with PBDB will make the process of sharing your data easier.

### **Top Resources**

-   PBDB can be accessed via their [website](https://paleobiodb.org/), [mobile applications](https://paleobiodb.org/#/resources), and an [API](https://paleobiodb.org/data1.2/).

-   The PBDB website has a [Resources](https://paleobiodb.org/#/resources) tab where more information about these access points can be found. 

-   The same Resources page also includes information on how to contribute taxonomic information to PBDB. Lessons are available via a [playlist of YouTube](https://www.youtube.com/watch?v=C06cjzcSDq4&list=PLmOEA6rrJ1dc3a4-etDDGQ7tQG1sEK0g6) videos. Note that you will need to be granted Contributory User access to contribute to PBDB. More information about the process and different user types is available in the [PBDB User Guide](https://escholarship.org/content/qt6tm05630/qt6tm05630.pdf?t=s0797i).

## World Register of Marine Species (WoRMS)

### What Is It?

The World Register of Marine Species (WoRMS) is an authoritative and comprehensive list of names of marine organisms. It provides detailed information about marine species from around the world, helping anyone interested in marine life to find accurate and up-to-date information about these species, including where they can be found, their characteristics, and how they are related to one another. 

### **Why?**

-   WoRMS content is curated by taxonomic and thematic experts, not by database managers. 

-   Each taxonomic group is represented by an expert who has the authority over the content, and is responsible for controlling the quality of the information. Each of these main taxonomic editors can invite several specialists of smaller groups within their area of responsibility to join them. 

-   WoRMS is the taxonomic database used by OBIS, and other important biological initiatives.

### **Top Resources**

-   WoRMS and its associated tools can be explored via [web browser](https://www.marinespecies.org/index.php) or the WoRMS [API](https://www.marinespecies.org/rest/)

-   R packages: [worrms](https://cran.r-project.org/web/packages/worrms/index.html), [taxize](https://cran.r-project.org/web/packages/taxize/)

-   [Python package](https://github.com/iobis/pyworms)

## Habitat Classification

### What is it?

Habitat classification is the process of organizing quantitative observations (i.e., data collected by various methods and instruments) about the natural world into meaningful, human-understandable representations and descriptions. Habitat classification standards or systems provide terminology and methodology or guidance so that classification can be performed in a standard manner by individual projects and programs.

From [CMECS](https://repository.library.noaa.gov/view/noaa/27552) p. 2: “The purpose of habitat classification is “to provide a language through which data and information regarding habitats can be communicated and managed” (McDougall, Janowicz, and Taylor 2007).”

Similarities and differences between vocabularies, when to use each one? These are legitimate ‘vocabularies’ as opposed to an ontology.  From a perspective of making data interoperable, using these terms, but specifically the ENVO version (which would be more specific) will help data be more interoperable over time.

### Why?

CMECS (and the NVC and Wetlands standards) were endorsed by the US FGDC so that data collectors and analysts can describe data using standard terminology and organization structures. This enables data discovery and thereby data use and re-use of Federally funded data assets. Standardized classifications of observational data also allows the information derived from individual projects to be compared with each other and compiled into larger and more extensive representations across space and time. This advances the collective scientific knowledge of natural systems and enables coordinated management activities, such as regional assessments, monitoring and restoration between partners.

Combined with international ontologies like ENVO, which is used by UNESCO, for example, the reach of your data will become global.

## CMECS

### **What is it?** 

The [Coastal and Marine Ecological Classification Standard](https://iocm.noaa.gov/standards/cmecs-home.html) (CMECS) is a structured dictionary of terms that describe benthic habitats in marine, estuarine, and lacustrine settings. It was developed by a consortium of scientists and coastal managers to meet the needs of inventorying, monitoring and managing natural resources in US and territorial waters. CMECS terms are organized in a spatially-scaled framework for annotating geospatial data and integrating information about the physical components of aquatic habitats that enables three-dimensional representations of ecological conditions for associating with faunal behavior.

### **Why should you use it?**

CMECS is endorsed as a Federal Geographic Data Committee (FGDC) standard in the U.S. and should be used by all federally funded projects that involve aquatic environmental data. Using CMECS allows for broader analytical applications of data.

### **How to use it?** 

You can read more about the CMECS standard, how to use it (including examples), and how to contribute to the improvement of CMECS by visiting [this website](https://iocm.noaa.gov/standards/cmecs-home.html).

## NVCS

### **What is it?**

The U.S National Vegetation Classification (USNVC) is a comprehensive classification system for all vegetation types in the United States. Much like a flora for plant species, the USNVC offers a hierarchy of classification levels from coarse to fine, providing a common language for the effective management and conservation of plant communities in the U.S. Furthermore, it is governed by standards for vegetation data collection and analysis, ensuring consistent reporting on the nation’s vegetation resources. 

The USNVC provides a common language for the effective management and conservation of plant communities. A collaboration between the [Ecological Society of America (ESA)](https://www.esa.org/vegpanel/), [NatureServe](https://www.natureserve.org/conservation-tools/projects/us-national-vegetation-classification), and [various federal agencies](https://usnvc.org/about/team/), the USNVC is the only standardized vegetation classification system for the United States. The framework of the standard allows for communication and cooperation on vegetation management issues that cross jurisdictional boundaries.

As a dynamic standard, the USNVC is designed to be easily adapted as new ecological knowledge becomes available. This as well as its hierarchical nature makes the classification scalable for diverse applications from vegetation monitoring to broad-scale analyses of trends across North America. Additional applications include:

-   Modeling and mapping wildlife habitat

-   Enhancing natural resource conservation efforts 

-   Fire management planning and modeling

-   Studying patterns of vegetation change over time 

-   Managing invasive species

-   Land inventory and mapping programs 

-   Setting national vegetation policies (e.g., biofuels, carbon markets, ecosystem services)

### **Why should you use it?**

Land management agencies are actively engaged in inventory and monitoring vegetation resources across the nation.  However, while vegetation classification is integral to the successful functioning of a variety of groups across all jurisdictional boundaries, no single agency has been tasked with the sole purpose of mapping or describing vegetation in the United States. As a result, many agencies have created their own protocols, resulting in data that is incompatible across jurisdictional boundaries. The USNVC was created to address this need.

### **How to use it?**

-   Details

    -   <https://usnvc.org/>

    -   <https://www.esa.org/vegpanel/resources/outreach-and-education/>

## NWCS

### **What is it?**

The primary objective of the Classification of Wetlands and Deepwater Habitats of the United States, as originally drafted by Cowardin et al. (1979:3), was “to impose boundaries on natural ecosystems for the purposes of inventory, evaluation, and management.” The FGDC Wetlands Classification Standard (WCS) provides minimum requirements and guidelines for classification of both wetlands and deepwater habitats that are consistent with the FGDC Wetlands Mapping Standard (FGDC-STD-015-2009). 

### **Why should you use it?**

The Classification of Wetlands and Deepwater Habitats of the United States (Cowardin et al. 1979) was developed to support a detailed inventory and periodic monitoring of the Nation’s wet habitats using remote sensing. It became a National Standard in 1996 (FGDC-STD-004), but has been the de facto standard for mapping U.S. wetlands and deepwater habitats since 1976

### **How to use it?**

-   Details

    -   <https://www.fgdc.gov/standards/projects/wetlands/index_html>

    -   <https://www.fgdc.gov/standards/projects/wetlands/nwcs-2013>

    -   <https://www.fws.gov/program/national-wetlands-inventory/classification-codes>

## Controlled Vocabularies

### What is it?

Controlled vocabulary are predefined, preferred terms or definitions that describe a specific entity, collection, parameter or unit of measurement to standardize information. They are used for indexing and annotating data and associated information (metadata) in database and data files. Controlled vocabularies have been carefully preselected by the designers of the specific schema.

There are processed through community groups and should be responsive to community needs.  You can get involved in them.

### Why should you use it?

Controlled vocabularies facilitate searching for data in web portals, and enable records to be interpreted by computers, facilitating automated data workflows, computer aided manipulation, distribution, and interoperability. They reduce ambiguity around terms, where the same concept can be given multiple names. Including controlled vocabulary ensures consistency, facilitates machine and human information retrieval and long-term reuse.

### **Controlled Vocabularies to Know About**

## [ENVO](https://sites.google.com/site/environmentontology/Browse-EnvO): Environmental Ontology

### **What is it?**

Ontology describes a set of concepts or categories in a domain and shows their properties and the relations between them. The Environmental Ontology (ENVO) is a domain ontology of environmental systems, ecosystems, components and processes to increase the interoperability of environmental descriptions. Additional information on ENVO can be found in the Wiki’s on their [GitHub repository](https://github.com/EnvironmentOntology/envo).

### **Why should you use it?**

While it started out as a relatively simple controlled and structured vocabulary to support the metadata checklist of the Genomic Standards Consortium (GSC), it has matured to support a wide range of initiatives ranging from individual research projects to inter-governmental data. This evolution is further guided by collaborations between the ESIP Federation, UN Environmental and IOC-UNESCO. ENVO now provides a comprehensive standardized vocabulary for describing habitats, ecosystems and environmental processes. 

Used internationally - global reach vs. US-reach. 

ENVO = controlled vocabulary + relationships + more…

### **How to use it?**

ENVO can be used to annotate data or metadata records in many ways. Every annotation should contain either:

-   The full internationalized resource identifier (IRI) of the term used (e.g. [**http://purl.obolibrary.org/obo/ENVO_01000228**](http://purl.obolibrary.org/obo/ENVO_01000228))

-   The CURIE form of the terms’ identifier (e.g. ENVO:01000228)

The IRI and identifier are locked to the definition or semantics of the term and don’t change. ENVO terms can also be used within the MIxS metadata standard (see [here](https://github.com/EnvironmentOntology/envo/wiki/ENVO-annotations-for-MIxS-v5)), for example to describe the materials that compose your sample or the environment where the sample was collected.

Several portals and ontology browsing interfaces already harvest from ENVO.

## [NERC ](https://vocab.nerc.ac.uk/): National Environmental Research Council

### **What is it?**

The NVS gives access to standardized and hierarchically-organized vocabularies. It is managed by the British Oceanographic Data Centre at the National Oceanography Centre (NOC) in Liverpool and Southampton, and receives funding from the Natural Environment Research Council (NERC) in the United Kingdom.

### **Why should you use it?**

By connecting terms held in controlled lists using standards, the data described by these controlled vocabularies become more interoperable and hence more broadly reusable. It becomes possible to build a truly distributed and interoperable data ecosystem across domain boundaries, enabling data reuse no matter the purpose for which they were collected in the first place.

### **How to use it?**

The [NVS Search (nerc.ac.uk)](https://vocab.nerc.ac.uk/search_nvs/) can be used to find controlled vocabulary terms

## Global Change Master Directory (GCMD) Keywords

### **What is it?**

The Global Change Master Directory (GCMD) Keywords are a standardized set of terms used to describe Earth science data sets and services. They serve as a common language for categorizing and searching for data related to Earth science, environmental science, and global change research

### **Why should you use it?**

GCMD Keywords provide a standardized vocabulary for describing Earth science data, ensuring consistency and interoperability across different data sets and repositories. The GCMD keywords describe Earth science data and services consistently and comprehensively in a hierarchical format and follow a codified governance process. The power of the keywords is in their ability to enable scientists to tag their data using a taxonomy of controlled scientific categories. This, in turn, allows those searching for data to discover datasets easily through the use of an established hierarchy.

### **How to use it?**

Global Change Master Directory (GCMD) Keywords are a hierarchical set of controlled Earth Science vocabularies that help ensure Earth science data, services, and variables are described in a consistent and comprehensive manner and allow for the precise searching of metadata and subsequent retrieval of data, services, and variables. Initiated over twenty years ago, GCMD Keywords are periodically analyzed for relevancy and will continue to be refined and expanded in response to user needs. The categories of GCMD Keywords are as follows:

-   Earth Science

-   Earth Science Services

-   Data Centers/Service Providers

-   Projects

-   Instruments/Sensors

-   Platforms/Sources

-   Locations

-   Horizontal Data Resolution

-   Vertical Data Resolution

-   Temporal Data Resolution

-   URL Content Types

-   Granule Data Formats

-   Measurement Names

-   Chronostratigraphic Units

More information can be found here:[Global Change Master Directory (GCMD) Keywords \| Earthdata (nasa.gov)](https://www.earthdata.nasa.gov/learn/find-data/idn/gcmd-keywords)
