# Introduction

*This is still a work in progress and only presented here for the purposes of receiving feedback. This message will be removed when the best practices have been officially published.*

The diversity of biological data, and (seeming) lack of overarching community standards makes working with biological data challenging. Several standards do exist for biological data, however these different data, metadata, and taxonomic standards are confusing for data managers and data users to navigate. The biological data community in the US could benefit from guidance, best practice documentation, training, and community building. The [ESIP Biological Data Cluster (BDS)](https://wiki.esipfed.org/Biological_Data_Standards_Cluster) was formed to tackle these problems.

In short, the will be successful if it:

1.  Increase awareness & interest in standards
2.  Create unity/shared vision around biological data standards implementation & Provide guidance related to biological standards
3.  Provide opportunities for Knowledge sharing & coordination
4.  Provide Connectivity across ESIP

We successfully increased awareness and interest in standards through the creation of the primer, officially called, [Biological Observation Data Standardization - A Primer for Data Manager](https://doi.org/10.6084/m9.figshare.16806712.v1) Our goals have evolved to work toward creating a sample extension of the cluster's primer in the form of a best practice document(s). The target audience for the best practice document(s) are people who are new to working with biological data standards. The best practice document will provide additional detail on the points listed in the primer, focusing on efficient actions that can be taken to standardize data.

\newpage

As an example, we brainstormed the "Make your data software ready" section of the primer. Specifically, this includes:

-   Use non-proprietary formats
-   Structure data in tidy/long format
-   Follow ISO 8601 for dates
-   Match scientific names to a taxonomic authority
-   Record latitude and longitude in decimal degrees in WGS84
-   Use globally unique identifiers

The proposed structure for each guide module is:

-   Value proposition (Why?)
-   List / key information (bulleted)
-   References list (max 5)
